//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFahWebsite.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBrand
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Img { get; set; }
        public int CatId { get; set; }
        public bool Isactive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
