//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFahWebsite.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCategory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool Isactive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
