//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFahWebsite.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProDetail
    {
        public int Id { get; set; }
        public int PrdId { get; set; }
        public string Detail { get; set; }
        public string Color { get; set; }
        public string Style { get; set; }
    }
}
