//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFahWebsite.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSale
    {
        public int Id { get; set; }
        public int BrndId { get; set; }
        public int PrdId { get; set; }
        public decimal Sale { get; set; }
        public decimal ExFac { get; set; }
        public decimal Discount { get; set; }
        public Nullable<System.DateTime> DiscountTillDate { get; set; }
        public Nullable<decimal> Sold { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public string User { get; set; }
        public bool isactive { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Mod_Text { get; set; }
    
        public virtual TblBrand TblBrand { get; set; }
        public virtual TblProduct TblProduct { get; set; }
    }
}
